module Unicon
  # Model names a host app may look up, each naming the concept it takes its icons from
  ALIASES = {
    address: :pin, agent: :badge, alert: :warning, announcement: :megaphone,
    answer: :question, api: :terminal, app: :window, appointment: :calendar_check,
    area: :map, assessment: :clipboard, attachment: :paperclip, audio: :waveform,
    avatar: :account, backup: :cloud, banner: :image, bill: :invoice,
    booking: :calendar_check, brand: :building, business: :building, call: :phone,
    campaign: :megaphone, category: :tag, charge: :credit_card, city: :building,
    client: :person, comment: :chat, company: :building, configuration: :gear,
    contract: :signature, conversation: :chat, cost: :cash, country: :globe,
    county: :map, coupon: :gift, credential: :key, customer: :person,
    dashboard: :speedometer, deadline: :alarm, delivery: :truck, destination: :pin,
    discount: :percent, echo: :waveform, email: :envelope, employee: :badge,
    episode: :playlist, evaluation: :speedometer, event: :calendar, export: :download,
    feedback: :smiley, file: :document, fleet: :truck, form: :document,
    franchise: :shop, goal: :trophy, group: :people, history: :clock,
    home: :house, import: :upload, integration: :puzzle, inventory: :box,
    issue: :warning, item: :box, job: :hammer, label: :tag,
    lead: :person, location: :pin, log: :list, market: :map,
    member: :person, memo: :note, message: :chat, milestone: :flag,
    movie: :video, notification: :bell, offer: :gift, office: :building,
    optimization: :sliders,
    order: :cart, organization: :building, package: :box, page: :document,
    password: :lock, payment: :credit_card, permission: :key, photo: :image,
    picture: :image, plan: :calendar, platform: :puzzle, plugin: :puzzle,
    preference: :sliders, price: :tag, product: :box, profile: :account,
    project: :folder, prompt: :terminal, provider: :briefcase, purchase: :cart,
    rating: :star, recording: :microphone, region: :map, reminder: :bell,
    review: :star, ride: :car, role: :badge, route: :signpost,
    schedule: :calendar, screen: :display, session: :clock, setting: :gear,
    shift: :clock, shipment: :truck, site: :globe, source: :signpost,
    specialty: :award, staff: :people, state: :map, subscription: :repeat,
    summary: :document, supplier: :truck, survey: :clipboard, sync: :refresh,
    team: :people, territory: :map, todo: :task, token: :key,
    track: :music, transaction: :credit_card, trip: :map, user: :person,
    vehicle: :car, vendor: :shop, vertical: :bar_chart, view: :eye,
    zip: :pin,
  }.freeze
end
